# Generated by Django 4.1.3 on 2022-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_address_publisher_book_publisher_publisher_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterModelTable(
            name='book',
            table='',
        ),
    ]
