# Generated by Django 4.1.3 on 2022-11-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options_alter_book_edition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
